#!/bin/dash

# check repo is initalised
 if [ ! -d .tigger ];then 
    >&2 echo "tigger-checkout: error: tigger repository directory .tigger not found"
    exit 1
fi

# check that there have been commits
if find .tigger/commits/  -maxdepth 0 ! -empty | ifne false; then
    >&2 echo "tigger-checkout: error: this command can not be run until after the first commit"
    exit 1
fi

# check the usage
if ! [ "$#" -eq 1 ]; then
    >&2 echo "usage: tigger-checkout <branch>"
    exit 1
fi

# check the branch exists
if ! [ -d .tigger/branches/"$1"  ]; then
    >&2 echo "tigger-checkout: error: unknown branch '$1'"
    exit 1
fi


# Create variables to access directories

BRANCH="$(find .tigger/branches/.head/ -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)"
BRANCHINDEX="$(find ./.tigger/branches/.head/"$BRANCH"/ -type f  -printf "%f\n" | sort -r | head -1)"

if [ $1 = "$BRANCH" ]; then
    >&2 echo "Already on '$1'"
    exit 1
fi
TARGETBRANCH="$1"


if  diff .tigger/branches/"$BRANCH"/.commitindex .tigger/branches/"$TARGETBRANCH"/.commitindex >/dev/null; then
    continue
    # mkdir -p .tigger/.headinfo
    # mv .tigger/branches/.head/"$BRANCH" .tigger/.headinfo
    # if ! mv .tigger/.headinfo/"$TARGETBRANCH" tigger/branches/.head/ 2>/dev/null; then
    #     mkdir .tigger/branches/.head/$TARGETBRANCH && touch .tigger/branches/.head/$TARGETBRANCH/0
    # fi
    #     echo "Switched to branch '$TARGETBRANCH'"
    # exit 0

else

    for file in $(basename -a $(find .tigger/branches/$BRANCH -type f )); do
        # if [ $file = ".commitindex" ] || [ $file = ".branchindex" ];then
        #     continue
        # fi
        # #     #if the file is not shared remove it from the repo?
        if ! [ -f .tigger/$TARGETBRANCH/$file ]; then

            rm -f $file 
        # MAYBE LOG THE FILES INCASE WE HAVE TO RESTORE THEM
        fi
    done

    for file in $(basename -a $(find  .tigger/branches/$TARGETBRANCH -type f )); do
        if [ $file = ".commitindex" ] || [ $file = ".branchindex" ];then
            continue
        fi
        cp .tigger/branches/$TARGETBRANCH/$file .
    done


fi

    mkdir -p .tigger/.headinfo
    cp -R .tigger/branches/.head/"$BRANCH" .tigger/.headinfo
    rm -r .tigger/branches/.head/"$BRANCH"
    if ! cp -R .tigger/.headinfo/"$TARGETBRANCH" tigger/branches/.head/ 2>/dev/null; then
        mkdir .tigger/branches/.head/$TARGETBRANCH && touch .tigger/branches/.head/$TARGETBRANCH/0
    else
    rm -r .tigger/.headinfo/"$TARGETBRANCH"
    fi
    echo "Switched to branch '$TARGETBRANCH'"
    exit 0

# if a file is untrack leave it

