#!/bin/dash

# check that the repo exists
if  [ ! -d .tigger ];then
    echo "tigger-add: error: tigger repository directory .tigger not found" 
    exit 1
fi

# check the usage
if [ $# -lt 1 ]; then
    echo "usage: tigger-add <filenames>"
fi


# Verbose but safe way of getting the branch name of the current head 
BRANCH="$(find .tigger/branches/.head/ -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)"
BRANCHINDEX="$(find ./.tigger/branches/.head/"$BRANCH"/ -type f  -printf "%f\n" | sort -r | head -1)"
HEAD=."$BRANCH"."$BRANCHINDEX"

# error checking loop first
for file in "$@"; do

    # check filename characters
    if ! echo "$file" | grep -Ei '^[a-z0-9_.-]*$' > /dev/null; then 
        echo "tigger-add: error: invalid filename '$file'"
        exit 1
    fi

    # check the file doesn't start with certain characters
    if echo "$file" | grep -Ei '^([_]|[.])' >/dev/null; then
        echo "tigger-add: error: invalid filename '$file'"
        exit 1
    fi


    #check file exists
    if [ ! -f "$file" ] && [ ! -f .tigger/index/"$HEAD"/"$file" ]; then
        echo "tigger-add: error: can not open '$file'"
        exit
    fi
done

# implmentation loop
for file in "$@"; do

    mkdir -p .tigger/index/"$HEAD"
    
    # Either add or remove the file from the index
    if [ -f "$file" ]; then 
        cp "$file" .tigger/index/"$HEAD" 2>/dev/null
    else 
        rm -f .tigger/index/"$HEAD"/"$file" 2>/dev/null
    fi
done

### NOTE ONLY ADDED FOR SUBSET 2 ###
mkdir -p .tigger/changes
cp -r .tigger/index/"$HEAD"/* .tigger/changes
