#!/bin/dash

#check the repo exists
if  [ ! -d .tigger ];then
    >&2 echo "tigger-add: error: tigger repository directory .tigger not found" # stder
    exit 1
fi

if [ $# -gt 0 ]; then
    1>&2 echo "usage: tigger-log"
    exit 1
fi
BRANCH="$(find .tigger/branches/.head/ -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)"

sort -r < .tigger/branches/.head/"$BRANCH"/.log | uniq
